version: "2.4"
services:
  app:
    image: malwinakunam/my-1st-blog:latest
    ports:
      - "81:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=root
      - MYSQL_DATABASE=new_schema_blog
      - MYSQL_PORT=3306

  mysql:
    image: mysql:5
    ports:
      - "63306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - type: volume
        target: /var/lib/mysql
        source: mysql_data
volumes:
  mysql_data:
    driver: local
