version: "2.4"
services:
  mysql:
    image: mysql:5
    ports:
      - "63306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Secret123
    volumes:
      - type: volume
        target: /var/lib/mysql  
        source: mysql_data     
volumes:
  mysql_data:
    driver: local
